 apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: <email>
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-secret-prd
  namespace: default
spec:
  secretName: tls-secret-prd
  dnsNames:
    - <domain>
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - <domain>
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer